apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: aevmb0thn-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/aevmb0thn-java-quarkus-gitops